#!/bin/bash

# Dynamic MOTD 
# 1. Disable system motd. 
# 2. save this dynmotd to /usr/local/bin/dynmotd    (chmod +x)
# 3. add '/usr/local/bin/dynmotd' in /etc/profile

# disabling MOTD
# /etc/ssh/sshd_config:    PrintMotd no
# /etc/pam.d/login:     #session    optional   pam_motd.so

C_NO="\033[0m"		# no colour

C_BLACK="\033[0;30m"
C_GRAY="\033[1;30m"
C_RED="\033[0;31m"
C_GREEN="\033[0;32m"
C_DARK_SLATE_BLUE="\033[0;33m"
C_YELLOW="\033[1;33m"
C_BLUE="\033[0;34m"
C_STEEL_BLUE="\033[1;34m"
C_VOILET="\033[0;35m"
C_DARK_VOILET="\033[0;36m"
C_CYAN="\033[1;36m"
C_WHITE="\033[1;37m"


C_L_RED="\033[1;31m"	# light red
C_L_GREEN="\033[1;32m"
C_L_GRAY="\033[0;37m"	# light gray
C_L_VOILET="\033[1;35m"		# light voilet
C_L_CYAN="\033[1;36m"		# light cyan

#$C_VOILET++++++++++++++++++:$C_L_GRAY User Data $C_VOILET:++++++++++++++++++++
echo -e "$C_YELLOW`cat /etc/motd-logo`
$C_VOILET+++++++++++++++++:$C_L_GRAY System Info $C_VOILET:+++++++++++++++++++
$C_VOILET+$C_L_GRAY Hostname $C_VOILET=$C_GREEN `hostname`
$C_VOILET+$C_L_GRAY Uptime   $C_VOILET=$C_GREEN `uptime | sed 's/.*up ([^,]*), .*/1/'`
$C_VOILET+$C_L_GRAY Username $C_VOILET=$C_GREEN `whoami`
$C_VOILET+++++++++++++:$C_L_GRAY Helpful Information $C_VOILET:+++++++++++++++
$C_GRAY modify /etc/motd-hellp to show info here. 
$C_GREEN`cat /etc/motd-help`

$C_VOILET+++++++++++:$C_L_GRAY Maintenance Information $C_VOILET:+++++++++++++
$C_GRAY modify /etc/motd-maint to show info here.
$C_L_RED`cat /etc/motd-maint`$C_NO"
